//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Core.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_person
    {
        public int contact_person_id { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string comment { get; set; }
        public Nullable<int> person_id_delete { get; set; }
        public Nullable<int> company_id { get; set; }
        public string fundet_vha { get; set; }
        public string our_sales_person { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> julebrev { get; set; }
        public Nullable<byte> moment_abonnement { get; set; }
        public Nullable<System.DateTime> moment_startdato { get; set; }
        public System.DateTime createdDate { get; set; }
        public string our_meeting_booker { get; set; }
        public int karriere_partner_code { get; set; }
        public string key_account_manager { get; set; }
        public string kmo { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> sales_person_id { get; set; }
        public bool nps_unsubscribe { get; set; }
        public string guid { get; set; }
        public string password { get; set; }
        public bool nps_subscribe { get; set; }
        public bool portal_hours { get; set; }
        public bool portal_invoice { get; set; }
        public bool portal_planning { get; set; }
    
        public virtual company company { get; set; }
    }
}
