//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Core.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db12054Entities : DbContext
    {
        public db12054Entities()
            : base("name=db12054Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobToContactPerson> JobToContactPersons { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<contact_person> contact_person { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<vReportedHour> vReportedHours { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<vTask> vTasks { get; set; }
    }
}
