//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Core.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_id { get; set; }
        public int file_number { get; set; }
        public string invoice_name { get; set; }
        public string name { get; set; }
        public Nullable<byte> job_status { get; set; }
        public string public_description { get; set; }
        public string internal_description { get; set; }
        public bool active { get; set; }
        public string hours_per_week { get; set; }
        public string estimated_total_hours { get; set; }
        public string deadline { get; set; }
        public double negotiated_price { get; set; }
        public string price_group { get; set; }
        public Nullable<int> recruitment_price { get; set; }
        public Nullable<byte> job_location { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string comments { get; set; }
        public string log_of_events { get; set; }
        public Nullable<int> company_id { get; set; }
        public string city { get; set; }
        public Nullable<byte> show { get; set; }
        public Nullable<int> contact_person_id { get; set; }
        public Nullable<System.DateTime> expected_end_date { get; set; }
        public string our_consultant { get; set; }
        public string our_consultant2 { get; set; }
        public string our_responsible { get; set; }
        public Nullable<byte> department { get; set; }
        public Nullable<System.DateTime> ended_date { get; set; }
        public Nullable<int> daily_contact_person_id { get; set; }
        public Nullable<int> treasury_contact_person_id { get; set; }
        public Nullable<int> cc_contact_person_id { get; set; }
        public Nullable<byte> job_category_single_id { get; set; }
        public bool bNeverEvaluate { get; set; }
        public Nullable<System.DateTime> dNextEvaluation { get; set; }
        public int recipients { get; set; }
        public byte[] searchCriteria { get; set; }
        public bool conditionsSent { get; set; }
        public string primarySalesPerson { get; set; }
        public string secondarySalesPerson { get; set; }
        public string meetingBooker { get; set; }
        public string keyAccountManager { get; set; }
        public Nullable<int> primarySalesPersonPercentage { get; set; }
        public Nullable<int> secondarySalesPersonPercentage { get; set; }
        public Nullable<int> meetingBookerPercentage { get; set; }
        public Nullable<int> keyAccountManagerPercentage { get; set; }
        public Nullable<System.DateTime> applicationDeadline { get; set; }
        public string InvoiceAddress { get; set; }
        public Nullable<int> InvoiceAddressZipNumber { get; set; }
        public string InvoiceReference { get; set; }
        public Nullable<double> SalaryBase { get; set; }
        public string TimeregName { get; set; }
        public Nullable<int> jobCategoryNew { get; set; }
        public string ExposedOn { get; set; }
        public Nullable<int> MaleFemale { get; set; }
        public Nullable<bool> OnKRFrontpage { get; set; }
        public Nullable<System.DateTime> ReportingLockedBefore { get; set; }
        public Nullable<System.DateTime> LastCheckedDate { get; set; }
        public Nullable<System.DateTime> TimeSpecMailSentDate { get; set; }
        public string InvoiceAddress2 { get; set; }
        public string TeaserText { get; set; }
        public Nullable<int> JobMailSortCategoryID { get; set; }
        public bool SpecialInvoice { get; set; }
        public Nullable<bool> TermsOfSaleSent { get; set; }
        public bool ShowInHRP { get; set; }
        public string scanTag { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> jobTemplateSubstitutionConfirmation { get; set; }
        public Nullable<int> jobTemplateCoverLetterSingle { get; set; }
        public Nullable<int> jobTemplateCoverLetterBoth { get; set; }
        public Nullable<int> workPeriod_id { get; set; }
        public Nullable<System.DateTime> EarliestStart { get; set; }
        public Nullable<System.DateTime> ApplicationEndDate { get; set; }
        public string heading { get; set; }
        public Nullable<System.DateTime> JobNewsletterResetFrom { get; set; }
        public Nullable<System.DateTime> Application_Startdate { get; set; }
        public string Zip_String { get; set; }
        public Nullable<int> Repost_Job_Id { get; set; }
        public Nullable<int> Reason_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> wage_type_id { get; set; }
        public int job_category_intern_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string ean { get; set; }
        public bool show_on_jobbanks { get; set; }
        public Nullable<System.DateTime> unanonymous_date { get; set; }
        public Nullable<int> hirevue_id { get; set; }
        public string weOffer1 { get; set; }
        public string weOffer2 { get; set; }
        public string weOffer3 { get; set; }
        public string workHoursAndSalary { get; set; }
        public Nullable<int> highlightId { get; set; }
        public Nullable<int> primaryCategoryId { get; set; }
        public Nullable<int> employeeCount { get; set; }
        public bool hideInInternalTimeregOverview { get; set; }
        public bool hideInDetailTabOnCostumerPortal { get; set; }
        public int autoBpBreakLimit { get; set; }
        public int autoBpBreakLength { get; set; }
        public bool midterm_invoice { get; set; }
        public Nullable<int> applicationType { get; set; }
        public Nullable<int> superJobId { get; set; }
        public Nullable<bool> hideInJoblist { get; set; }
        public Nullable<bool> motivationNeeded { get; set; }
        public string extraInvoiceEmail { get; set; }
        public string virksomheden { get; set; }
        public Nullable<int> jobcontractid { get; set; }
    }
}
