//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Core.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReportedHour
    {
        public int reported_hours_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string company { get; set; }
        public int jnr { get; set; }
        public string job_name { get; set; }
        public int student_id { get; set; }
        public string SSN { get; set; }
        public string worker { get; set; }
        public System.DateTime worked_date { get; set; }
        public int minutes { get; set; }
        public string period { get; set; }
        public int etc_id { get; set; }
        public int status { get; set; }
        public string consultants { get; set; }
    }
}
