//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerPortal.Core.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTask
    {
        public int jnr { get; set; }
        public int student_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public int state { get; set; }
        public int oncall { get; set; }
        public string vagttype { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public int task_id { get; set; }
        public string job_name { get; set; }
        public Nullable<bool> CheckedIn { get; set; }
        public int job_attribute_id { get; set; }
        public int job_id { get; set; }
    }
}
